stages:
  - stage_build
  - stage_test
  - stage_deploy

build_job:
    stage: stage_build
    tags: [my_runner]
    script:
        - echo "default image"

test_job: 
    stage: stage_test
    tags: [my_runner]
    image:
        name: hashicorp/terraform:1.5
        entrypoint: [""]
    script:
        - echo "terraform image"
        - terraform -version

deploy_job:
    stage: stage_deploy
    script:
        - echo "default image"