variables:
  DEBIAN_FRONTEND: noninteractive
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

stages:
  - build
  # - deploy

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""  # Відключаємо TLS для спрощення
  before_script:
    - apk add --no-cache bash curl
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    
  # artifacts:
  #   paths:
  #     - Back/target/minAuthProj-0.0.1-SNAPSHOT.jar  # Зберігаємо JAR на випадок, якщо потрібно для deploy
  #   expire_in: 1 day

# deploy_job:
#   stage: deploy
#   tags:
#     - runner
#   before_script:
#     - apt-get update && apt-get install -y docker.io ansible python3-pip
#     - pip3 install docker
#   script:
#     - ansible-playbook deploy-backend.yml -i inventory.ini -v -e imagetag=comithash
#   dependencies:
#     - build_job  # Залежність від етапу build, щоб отримати артефакт