stages:
  - test

test_time_job:
  stage: test
  tags:
    - my_runner
  image: python:3.9-slim
  before_script:
    - apt-get update -y
    - apt-get install -y ansible openssh-client
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - ansible-playbook -i inventory/inventory.yml node01 show_time.yml -u vagrant --private-key=~/.ssh/id_rsa
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY