variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - runner

  before_script:
    - apt-get update && apt-get install -y docker.io ansible python3-pip
    - pip3 install docker

  script:
    - ansible-playbook deploy-backend.yml -i inventory.ini -v