variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - runner

  script:
    - ip a s
    - ansible-playbook show_time.yml -i inventory.ini -vvv
  
    