variables:
  DEBIAN_FRONTEND: noninteractive
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  IMAGE_TAG: "$CI_REGISTRY_IMAGE/min-auth-proj:$CI_COMMIT_SHORT_SHA"

stages:
  - build
  - deploy

build_job:
  stage: build
  tags:
    - runner
  before_script:
    - apt-get update
    - apt-get install -y openjdk-21-jdk maven docker.io
    - rm -rf ~/.m2/repository/org/springframework/boot/
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$IMAGE_TAG" Back/
    - docker push "$IMAGE_TAG"
  cache:
    paths:
      - ~/.m2/repository/

deploy_job:
  stage: deploy
  tags:
    - runner
  needs:
    - job: build_job
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
  variables:
    DB_URL: "$DB_URL"
    DB_USER: "$DB_USER"
    DB_PASSWORD: "$DB_PASSWORD"
    MAIL_HOST: "$MAIL_HOST"
    MAIL_PORT: "$MAIL_PORT"
    MAIL_USERNAME: "$MAIL_USERNAME"
    MAIL_PASSWORD: "$MAIL_PASSWORD"
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
    REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/min-auth-proj"
    ANSIBLE_REPO_URL: 'https://gitlab.com/aVOKADO-hub/ansible_repo.git'
    ANSIBLE_CLONE_DIR: ansible_repo
    SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
  before_script:
    - apt-get update && apt-get install -y openssh-client git ansible
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ansible
    - chmod 600 ~/.ssh/id_ansible
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_CLONE_DIR"
  script:
    - ansible-playbook -i "$ANSIBLE_CLONE_DIR/inventory.ini" "$ANSIBLE_CLONE_DIR/deploy_docker.yml" \
      -e "registry_image=$REGISTRY_IMAGE" \
      -e "image_tag=$IMAGE_TAG" \
      -e "gitlab_db_url=$DB_URL" \
      -e "gitlab_db_user=$DB_USER" \
      -e "gitlab_db_password=$DB_PASSWORD" \
      -e "gitlab_mail_host=$MAIL_HOST" \
      -e "gitlab_mail_port=$MAIL_PORT" \
      -e "gitlab_mail_username=$MAIL_USERNAME" \
      -e "gitlab_mail_password=$MAIL_PASSWORD"
  after_script:
    - rm -f ~/.ssh/id_ansible
    - rm -rf "$ANSIBLE_CLONE_DIR"
  cache:
    paths:
      - ~/.cache/pip
      - ~/.ansible/