variables:
  DEBIAN_FRONTEND: noninteractive
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

stages:
  - build

build:
  stage: build
  tags: runner
  before_script:
    - apt-get update && apt-get install -y docker.io
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_TAG Back/
    - docker push $IMAGE_TAG