---
- name: Deploy Java backend and connect to PostgreSQL
  hosts: deploy_servers
  become: yes
  gather_facts: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Python module
      pip:
        name: docker
        state: present

    - name: Create Docker network (if not exists)
      docker_network:
        name: backend_network
        state: present

    - name: Copy Java project with Dockerfile to remote host
      copy:
        src: Back/
        dest: /tmp/backend/
        mode: '0755'

    - name: Ensure JAR file exists
      stat:
        path: /tmp/backend/target/minAuthProj-0.0.1-SNAPSHOT.jar
      register: jar_file
      failed_when: not jar_file.stat.exists

    - name: Debug JAR presence
      debug:
        msg: "Found JAR: {{ jar_file.stat.exists }}"

    - name: Build Java backend Docker image
      docker_image:
        name: java_backend_image
        build:
          path: /tmp/backend/
          dockerfile: Dockerfile
        source: build
        force_tag: true

    - name: Remove existing backend container if it exists
      docker_container:
        name: java_backend_container
        state: absent
        force_kill: true

    - name: Run Java backend container
      docker_container:
        name: java_backend_container
        image: java_backend_image:latest
        state: started
        ports:
          - "8080:8080"
        networks:
          - name: backend_network
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_db:5432/mydatabase"
          SPRING_DATASOURCE_USERNAME: "myuser"
          SPRING_DATASOURCE_PASSWORD: "secret"
          SPRING_DATASOURCE_DRIVER: "org.postgresql.Driver"

    - name: Check if
