@startuml
class Course {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String courseName;
    private String eventTimeAtEducationalDays;
    private String eventTimeAtWeekendsAndHolidays;

    @ManyToOne
    @JoinColumn(name = "schedule_id")
    private Schedule schedule;
}
@enduml